<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button-Continue</name>
   <tag></tag>
   <elementGuidId>7b704257-84ef-4dd2-a507-407471073062</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='payment-info-buttons-container']/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='payment-info-buttons-container']/input</value>
   </webElementProperties>
</WebElementEntity>
