<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button-Continue</name>
   <tag></tag>
   <elementGuidId>5e041680-064b-4da5-bea9-1cf9d51f6856</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@onclick='ShippingMethod.save()']
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@onclick='ShippingMethod.save()']
</value>
   </webElementProperties>
</WebElementEntity>
